<!DOCTYPE html>
<html lang='en'><head>
  <meta charset='utf-8'>
<meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='description' content='Mapping the effects of minimum wage changes in Ontario using R'>
<meta name='theme-color' content='#ffcd00'>

<meta property='og:title' content='Using Open Data to map Bill 148 effects • Rob Coleman'>
<meta property='og:description' content='Mapping the effects of minimum wage changes in Ontario using R'>
<meta property='og:url' content='https://robcoleman.ca/post/writeup/'>
<meta property='og:site_name' content='Rob Coleman'>
<meta property='og:type' content='article'><meta property='article:section' content='post'><meta property='article:tag' content='Open Data'><meta property='article:tag' content='Minimum wage'><meta property='article:published_time' content='2018-03-18T00:00:00Z'/><meta property='article:modified_time' content='2018-03-18T00:00:00Z'/><meta name='twitter:card' content='summary'><meta name='twitter:site' content='@coleman'>

<meta name="generator" content="Hugo 0.58.3" />

  <title>Using Open Data to map Bill 148 effects • Rob Coleman</title>
  <link rel='canonical' href='https://robcoleman.ca/post/writeup/'>
  
  
  <link rel='icon' href='/favicon.ico'>
<link rel='stylesheet' href='/assets/css/main.6a060eb7.css'><link rel='stylesheet' href='/css/custom.css'><style>
:root{--color-accent:#ffcd00;}
</style>

<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-73411487-1', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>

  

</head>
<body class='page type-post'>

  <div class='site'><a class='screen-reader-text' href='#content'>Skip to Content</a><div class='main'><nav id='main-menu' class='menu main-menu' aria-label='Main Menu'>
  <div class='container'>
    
    <ul><li class='item'>
        <a href='/'>Home</a>
      </li><li class='item'>
        <a href='/post/'>Code</a>
      </li><li class='item'>
        <a href='/notes/'>notes</a>
      </li><li class='item'>
        <a href='/books/'>books</a>
      </li><li class='item'>
        <a href='/about/'>About</a>
      </li></ul>
  </div>
</nav><div class='header-widgets'>
        <div class='container'></div>
      </div>

      <header id='header' class='header site-header'>
        <div class='container sep-after'>
          <div class='header-info'><p class='site-title title'>Rob Coleman</p><p class='desc site-desc'>Notes on data science, books and labour market policy</p>
          </div>
        </div>
      </header>

      <main id='content'>


<article lang='en' class='entry'>
  <header class='header entry-header'>
  <div class='container sep-after'>
    <div class='header-info'>
      <h1 class='title'>Using Open Data to map Bill 148 effects</h1>
      
<p class='desc'>Mapping the effects of minimum wage changes in Ontario using R</p>


    </div>
    <div class='entry-meta'>
  <span class='posted-on'><svg class='icon' viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
  
  <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/>
  <line x1="16" y1="2" x2="16" y2="6"/>
  <line x1="8" y1="2" x2="8" y2="6"/>
  <line x1="3" y1="10" x2="21" y2="10"/>
  
</svg>
<span class='screen-reader-text'>Posted on </span>
  <time class='entry-date' datetime='2018-03-18T00:00:00Z'>2018-03-18</time>
</span>

  
  

</div>


  </div>
</header>

  
  

  <div class='container entry-content'>
  

<p>I covered some interesting changes to minimum wage in my <a href="https://robcoleman.ca/blog/minimum-wage-changes-in-ontario/" target="_blank">last post</a>. I&rsquo;m trying to build my skills in the mapping department, so I&rsquo;m going to create an interactive map of the communities most affected by the change in minimum wage.</p>

<h2 id="loading-the-data">Loading the data</h2>

<p>The wage data is collected by the Canadian federal government and published as an <a href="https://open.canada.ca/data/en/dataset/adad580f-76b0-4502-bd05-20c125de9116" target="_blank">open dataset</a> available for download. The data is geographically organized by <a href="https://www.statcan.gc.ca/pub/92-195-x/2011001/geo/er-re/er-re-eng.htm" target="_blank">economic region</a>, so we&rsquo;ll need the shapefile for those boundaries which is also published as an <a href="https://open.canada.ca/data/en/dataset/c1242d53-3cef-4733-bafe-7492453c7e49" target="_blank">open dataset</a>!</p>

<pre><code>## Reading layer `ler_000b16a_e' from data source `c:\Users\rob\Documents\projects\minwage_map\map_data' using driver `ESRI Shapefile'
## Simple feature collection with 76 features and 4 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 3689439 ymin: 659338.9 xmax: 9015737 ymax: 5242179
## epsg (SRID):    NA
## proj4string:    +proj=lcc +lat_1=49 +lat_2=77 +lat_0=63.390675 +lon_0=-91.86666666666666 +x_0=6200000 +y_0=3000000 +datum=NAD83 +units=m +no_defs
</code></pre>

<h2 id="clean-the-wage-data">Clean the Wage data</h2>

<p>The data has a mix of wage types (hourly, annually) from a variety of sources. For my purposes I&rsquo;ll take the median wage for those occupations where it&rsquo;s reported hourly and ignore the annual data.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># clean data</span>
ON_wage_data <span style="color:#f92672">&lt;-</span> wage_data <span style="color:#f92672">%&gt;%</span>
  filter(PROV <span style="color:#f92672">==</span> <span style="color:#e6db74">&#34;ON&#34;</span>) <span style="color:#f92672">%&gt;%</span> <span style="color:#75715e">#filer ON results only</span>
  filter(<span style="color:#e6db74">`Annual Wage Flag_Salaire annuel`</span> <span style="color:#f92672">==</span> <span style="color:#ae81ff">0</span>) <span style="color:#f92672">%&gt;%</span> <span style="color:#75715e">#remove annual salaries</span>
  filter(<span style="color:#f92672">!</span><span style="color:#66d9ef">is.na</span>(<span style="color:#e6db74">`Median wage_Salaire Median`</span>)) <span style="color:#f92672">%&gt;%</span> <span style="color:#75715e">#remove occupations with missing data</span>
  filter(<span style="color:#f92672">!</span><span style="color:#e6db74">`ER Code_Code RE`</span> <span style="color:#f92672">==</span> <span style="color:#e6db74">&#34;ER35&#34;</span>) <span style="color:#f92672">%&gt;%</span> <span style="color:#75715e">#remove Ontario total</span>
  mutate(ERUID <span style="color:#f92672">=</span> str_sub(<span style="color:#e6db74">`ER Code_Code RE`</span>, start<span style="color:#f92672">=</span><span style="color:#ae81ff">3L</span>)) <span style="color:#75715e"># remove ER from ER Code so it can be joined</span>


<span style="color:#75715e"># how many low wage by community</span>

ON_wage_prop <span style="color:#f92672">&lt;-</span> ON_wage_data <span style="color:#f92672">%&gt;%</span>
  mutate(low_wage <span style="color:#f92672">=</span> case_when(
    <span style="color:#e6db74">`Median wage_Salaire Median`</span> <span style="color:#f92672">&lt;=</span> <span style="color:#ae81ff">14</span> <span style="color:#f92672">~</span> <span style="color:#ae81ff">1</span>,
    <span style="color:#66d9ef">TRUE</span> <span style="color:#f92672">~</span> <span style="color:#ae81ff">0</span>
  )) <span style="color:#f92672">%&gt;%</span> <span style="color:#75715e"># add a low wage indicator</span>
  group_by(<span style="color:#e6db74">`ERNAME`</span> <span style="color:#f92672">=</span> <span style="color:#e6db74">`ER Name_Nom RE`</span>, ERUID) <span style="color:#f92672">%&gt;%</span>
  summarise(total_occupations <span style="color:#f92672">=</span> n_distinct(NOC_CNP),
            total_low_wage <span style="color:#f92672">=</span> <span style="color:#66d9ef">sum</span>(low_wage)) <span style="color:#f92672">%&gt;%</span>
  mutate(prop_low_wage <span style="color:#f92672">=</span> <span style="color:#66d9ef">round</span>(total_low_wage <span style="color:#f92672">/</span> total_occupations <span style="color:#f92672">*</span> <span style="color:#ae81ff">100</span>)) <span style="color:#75715e"># compute the proportion of occupations that are low wage</span>

<span style="color:#75715e"># results</span>
ON_wage_prop <span style="color:#f92672">%&gt;%</span>
  arrange(desc(prop_low_wage)) <span style="color:#f92672">%&gt;%</span>
  kable()</code></pre></div>
<table>
<thead>
<tr>
<th align="left">ERNAME</th>
<th align="left">ERUID</th>
<th align="right">total_occupations</th>
<th align="right">total_low_wage</th>
<th align="right">prop_low_wage</th>
</tr>
</thead>

<tbody>
<tr>
<td align="left">London</td>
<td align="left">3560</td>
<td align="right">242</td>
<td align="right">31</td>
<td align="right">13</td>
</tr>

<tr>
<td align="left">Kingston&ndash;Pembroke</td>
<td align="left">3515</td>
<td align="right">194</td>
<td align="right">24</td>
<td align="right">12</td>
</tr>

<tr>
<td align="left">Northwest</td>
<td align="left">3595</td>
<td align="right">157</td>
<td align="right">19</td>
<td align="right">12</td>
</tr>

<tr>
<td align="left">Muskoka&ndash;Kawarthas</td>
<td align="left">3520</td>
<td align="right">170</td>
<td align="right">18</td>
<td align="right">11</td>
</tr>

<tr>
<td align="left">Toronto</td>
<td align="left">3530</td>
<td align="right">396</td>
<td align="right">39</td>
<td align="right">10</td>
</tr>

<tr>
<td align="left">Windsor&ndash;Sarnia</td>
<td align="left">3570</td>
<td align="right">222</td>
<td align="right">23</td>
<td align="right">10</td>
</tr>

<tr>
<td align="left">Hamilton&ndash;Niagara Peninsula</td>
<td align="left">3550</td>
<td align="right">337</td>
<td align="right">29</td>
<td align="right">9</td>
</tr>

<tr>
<td align="left">Northeast</td>
<td align="left">3590</td>
<td align="right">232</td>
<td align="right">22</td>
<td align="right">9</td>
</tr>

<tr>
<td align="left">Ottawa</td>
<td align="left">3510</td>
<td align="right">291</td>
<td align="right">26</td>
<td align="right">9</td>
</tr>

<tr>
<td align="left">Kitchener&ndash;Waterloo&ndash;Barrie</td>
<td align="left">3540</td>
<td align="right">335</td>
<td align="right">28</td>
<td align="right">8</td>
</tr>

<tr>
<td align="left">Stratford&ndash;Bruce Peninsula</td>
<td align="left">3580</td>
<td align="right">143</td>
<td align="right">12</td>
<td align="right">8</td>
</tr>
</tbody>
</table>

<h2 id="join-the-data">Join the data</h2>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># subset just ontario ERs</span>
ON_ERs <span style="color:#f92672">&lt;-</span> CAN_ERs <span style="color:#f92672">%&gt;%</span>
  filter(PRNAME<span style="color:#f92672">==</span> <span style="color:#e6db74">&#34;Ontario&#34;</span>)


<span style="color:#75715e">#see if it the subset worked</span>
plot(ON_ERs)</code></pre></div>
<p><a href="/img/ON.png"><img src="/img/ON.png" alt="" /></a></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#join the data to the boundary file</span>

merged_ON <span style="color:#f92672">&lt;-</span> <span style="color:#66d9ef">merge</span>(ON_ERs, ON_wage_prop, by <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;ERUID&#34;</span>)

<span style="color:#75715e">#did it work?</span>
<span style="color:#66d9ef">summary</span>(merged_ON)</code></pre></div>
<pre><code>##      ERUID                          ERNAME.x     PRUID   
##  3510   :1   Hamilton--Niagara Peninsula:1   35     :11  
##  3515   :1   Kingston--Pembroke         :1   10     : 0  
##  3520   :1   Kitchener--Waterloo--Barrie:1   11     : 0  
##  3530   :1   London                     :1   12     : 0  
##  3540   :1   Muskoka--Kawarthas         :1   13     : 0  
##  3550   :1   Northeast / Nord-est       :1   24     : 0  
##  (Other):5   (Other)                    :5   (Other): 0  
##                                                  PRNAME  
##  Ontario                                            :11  
##  Alberta                                            : 0  
##  British Columbia / Colombie-Britannique            : 0  
##  Manitoba                                           : 0  
##  New Brunswick / Nouveau-Brunswick                  : 0  
##  Newfoundland and Labrador / Terre-Neuve-et-Labrador: 0  
##  (Other)                                            : 0  
##    ERNAME.y         total_occupations total_low_wage  prop_low_wage  
##  Length:11          Min.   :143.0     Min.   :12.00   Min.   : 8.00  
##  Class :character   1st Qu.:182.0     1st Qu.:20.50   1st Qu.: 9.00  
##  Mode  :character   Median :232.0     Median :24.00   Median :10.00  
##                     Mean   :247.2     Mean   :24.64   Mean   :10.09  
##                     3rd Qu.:313.0     3rd Qu.:28.50   3rd Qu.:11.50  
##                     Max.   :396.0     Max.   :39.00   Max.   :13.00  
##                                                                      
##           geometry
##  MULTIPOLYGON :11  
##  epsg:NA      : 0  
##  +proj=lcc ...: 0  
##                    
##                    
##                    
##
</code></pre>

<h2 id="build-the-map">Build the map</h2>

<p>When I first started building the map with <code>leaflet</code> I kept getting this error:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">leaflet(merged_ON)  </code></pre></div>
<p><code>Warning messages: 1: sf layer is not long-lat data  2: sf layer has inconsistent datum (+proj=lcc +lat_1=49 +lat_2=77 +lat_0=63.390675 +lon_0=-91.86666666666666 +x_0=6200000 +y_0=3000000 +datum=NAD83 +units=m +no_defs). Need '+proj=longlat +datum=WGS84'</code></p>

<p>I used <code>st_transform</code> to change from <code>datum=NAD83</code> to <code>datum=WGS84</code></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">new_ON <span style="color:#f92672">&lt;-</span> st_transform(merged_ON, <span style="color:#e6db74">&#34;+proj=longlat&#34;</span>, <span style="color:#e6db74">&#34;+datum=WGS84&#34;</span>)</code></pre></div>
<p>That managed to allow me to use <code>leaflet</code> without throwing up an errors.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># set colours for cloropleth</span>
bins <span style="color:#f92672">&lt;-</span> <span style="color:#66d9ef">c</span>(<span style="color:#ae81ff">0</span>, <span style="color:#ae81ff">8</span>,<span style="color:#ae81ff">10</span>, <span style="color:#ae81ff">11</span>, <span style="color:#ae81ff">12</span>, <span style="color:#ae81ff">13</span>)
pal <span style="color:#f92672">&lt;-</span> colorBin(<span style="color:#e6db74">&#34;YlOrRd&#34;</span>, domain <span style="color:#f92672">=</span> new_ON<span style="color:#f92672">$</span>prop_low_wage, bins <span style="color:#f92672">=</span> bins)

<span style="color:#75715e"># create labels</span>
labels <span style="color:#f92672">&lt;-</span> <span style="color:#66d9ef">sprintf</span>(
  <span style="color:#e6db74">&#34;&lt;strong&gt;%s&lt;/strong&gt;&lt;br/&gt;%d total occupations &lt;br/&gt; %i total low wage occupations&#34;</span>,
  new_ON<span style="color:#f92672">$</span>ERNAME.y, new_ON<span style="color:#f92672">$</span>total_occupations, new_ON<span style="color:#f92672">$</span>total_low_wage
) <span style="color:#f92672">%&gt;%</span> <span style="color:#66d9ef">lapply</span>(htmltools<span style="color:#f92672">::</span>HTML)

map <span style="color:#f92672">&lt;-</span> leaflet(new_ON) <span style="color:#f92672">%&gt;%</span>
  addTiles() <span style="color:#f92672">%&gt;%</span>
  addPolygons(fillColor <span style="color:#f92672">=</span> <span style="color:#f92672">~</span>pal(prop_low_wage),
              color <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;white&#34;</span>,
              weight <span style="color:#f92672">=</span> <span style="color:#ae81ff">2</span>,
              opacity <span style="color:#f92672">=</span> <span style="color:#ae81ff">1</span>,
              fillOpacity <span style="color:#f92672">=</span> <span style="color:#ae81ff">0.55</span>,
              highlight <span style="color:#f92672">=</span> highlightOptions(
                weight <span style="color:#f92672">=</span> <span style="color:#ae81ff">3</span>,
                color <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;#666&#34;</span>,
                dashArray <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;&#34;</span>,
                fillOpacity <span style="color:#f92672">=</span> <span style="color:#ae81ff">0.7</span>,
                bringToFront <span style="color:#f92672">=</span> <span style="color:#66d9ef">TRUE</span>),
              label <span style="color:#f92672">=</span> <span style="color:#66d9ef">labels</span>,
              labelOptions <span style="color:#f92672">=</span> labelOptions(
                style <span style="color:#f92672">=</span> <span style="color:#66d9ef">list</span>(<span style="color:#e6db74">&#34;font-weight&#34;</span> <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;normal&#34;</span>, padding <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;3px 8px&#34;</span>),
                textsize <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;15px&#34;</span>,
                direction <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;auto&#34;</span>)) <span style="color:#f92672">%&gt;%</span>
  addLegend(<span style="color:#e6db74">&#34;topright&#34;</span>, pal <span style="color:#f92672">=</span> pal, values <span style="color:#f92672">=</span> <span style="color:#f92672">~</span>new_ON<span style="color:#f92672">$</span>prop_low_wage,
            title <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;% of low wage occupations&#34;</span>,
            labFormat <span style="color:#f92672">=</span> labelFormat(prefix <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;%&#34;</span>),
            opacity <span style="color:#f92672">=</span> <span style="color:#ae81ff">1</span>)</code></pre></div>
<h2 id="map-of-ontario-economic-regions-by-low-wage">Map of Ontario Economic Regions by Low Wage</h2>

<iframe seamless src="/leaflet/mymap.html" width="100%" height="500"></iframe>

<h2 id="references">References</h2>

<ul>
<li>Jesse Sadler&rsquo;s excellent <a href="https://www.jessesadler.com/post/gis-with-r-intro/" target="_blank">GIS Intro with R</a></li>
<li>The <code>sf</code> package <a href="https://cran.r-project.org/web/packages/sf/vignettes/sf1.html" target="_blank">vignette</a></li>
<li>A good discussion on <a href="http://www.nickeubank.com/wp-content/uploads/2015/10/RGIS2_MergingSpatialData_part1_Joins.html" target="_blank">merging spatial data</a></li>
<li>This repo was really helpful <a href="https://cengel.github.io/rspatial/" target="_blank">Intro to mapping and spatial analysis</a></li>
</ul>

</div>

  
<footer class='entry-footer'>
  <div class='container sep-before'><div class='tags'><svg class='icon' viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
  
  <path d="M20.59,13.41l-7.17,7.17a2,2,0,0,1-2.83,0L2,12V2H12l8.59,8.59A2,2,0,0,1,20.59,13.41Z"/>
  <line x1="7" y1="7" x2="7" y2="7"/>
  
</svg>
<span class='screen-reader-text'>Tags: </span><a class='tag' href='/tags/open-data/'>Open Data</a>, <a class='tag' href='/tags/minimum-wage/'>Minimum Wage</a></div>

  </div>
</footer>


</article>

<nav class='entry-nav'>
  <div class='container'><div class='prev-entry sep-before'>
      <a href='/post/minwage/'>
        <span aria-hidden='true'><svg class='icon' viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
  
  <line x1="20" y1="12" x2="4" y2="12"/>
  <polyline points="10 18 4 12 10 6"/>
  
</svg>
 Previous</span>
        <span class='screen-reader-text'>Previous post: </span>Minimum Wage Changes in Ontario</a>
    </div><div class='next-entry sep-before'>
      <a href='/post/commute/'>
        <span class='screen-reader-text'>Next post: </span>Analyzing Commuting Patterns in Ontario<span aria-hidden='true'>Next <svg class='icon' viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
  
  <line x1="4" y1="12" x2="20" y2="12"/>
  <polyline points="14 6 20 12 14 18"/>
  
</svg>
</span>
      </a>
    </div></div>
</nav>




      </main>

      <footer id='footer' class='footer'>
        <div class='container sep-before'><section class='widget widget-social_menu sep-after'><nav aria-label='Social Menu'>
    <ul><li>
        <a href='https://github.com/colemanrob' target='_blank' rel='noopener'>
          <span class='screen-reader-text'>Open Github account in new tab</span><svg class='icon' viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
  
  <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/>
  
</svg>
</a>
      </li><li>
        <a href='https://twitter.com/coleman' target='_blank' rel='noopener'>
          <span class='screen-reader-text'>Open Twitter account in new tab</span><svg class='icon' viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
  
  <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"/>
  
</svg>
</a>
      </li><li>
        <a href='https://instagram.com/robcoleman' target='_blank' rel='noopener'>
          <span class='screen-reader-text'>Open Instagram account in new tab</span><svg class='icon' viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
  
  <rect x="2" y="2" width="20" height="20" rx="5" ry="5"/>
  <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/>
  <line x1="17.5" y1="6.5" x2="17.5" y2="6.5"/>
  
</svg>
</a>
      </li><li>
        <a href='mailto:coleman.rob&#43;nospam@gmail.com' target='_blank' rel='noopener'>
          <span class='screen-reader-text'>Contact via Email</span><svg class='icon' viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
  
  <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/>
  <polyline points="22,6 12,13 2,6"/>
  
</svg>
</a>
      </li></ul>
  </nav>
</section><div class='copyright'>
  <p> &copy; 2017-2019 Rob Coleman </p>
</div>

        </div>
      </footer>

    </div>
  </div><script>window.__assets_js_src="/assets/js/"</script>

<script src='/assets/js/main.67d669ac.js'></script><script src='/js/custom.js'></script>

</body>

</html>

